/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ananta.apk;

/**
 *
 * @author HP
 */
public class TambahPaket extends javax.swing.JPanel {

    /**
     * Creates new form TambahPaket
     */
    public TambahPaket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shapecustom1 = new com.ananta.shapecustom.shapecustom();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        shapecustom2 = new com.ananta.shapecustom.shapecustom();
        shapecustom3 = new com.ananta.shapecustom.shapecustom();
        shapecustom4 = new com.ananta.shapecustom.shapecustom();
        shapecustom5 = new com.ananta.shapecustom.shapecustom();
        shapecustom6 = new com.ananta.shapecustom.shapecustom();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        shapecustom7 = new com.ananta.shapecustom.shapecustom();
        jLabel7 = new javax.swing.JLabel();
        shapecustom9 = new com.ananta.shapecustom.shapecustom();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        shapecustom10 = new com.ananta.shapecustom.shapecustom();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        shapecustom11 = new com.ananta.shapecustom.shapecustom();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Panel_TambahJasa1 = new com.ananta.shapecustom.shapecustom();
        Button_TambahJasa1 = new javax.swing.JButton();
        Ikon_TambahJasa1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(212, 212, 212));

        shapecustom1.setBackground(new java.awt.Color(255, 255, 255));
        shapecustom1.setRoundBottomLeft(80);
        shapecustom1.setRoundBottomRight(80);
        shapecustom1.setRoundTopLeft(80);
        shapecustom1.setRoundTopRight(80);

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 25)); // NOI18N
        jLabel3.setText("Jasa Dalam Package");

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 25)); // NOI18N
        jLabel2.setText("Nama Package");

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 30)); // NOI18N
        jLabel1.setText("Menu Tambah Package");

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 25)); // NOI18N
        jLabel4.setText("Harga");

        shapecustom2.setBackground(new java.awt.Color(212, 212, 212));
        shapecustom2.setRoundBottomLeft(40);
        shapecustom2.setRoundBottomRight(40);
        shapecustom2.setRoundTopLeft(40);
        shapecustom2.setRoundTopRight(40);

        javax.swing.GroupLayout shapecustom2Layout = new javax.swing.GroupLayout(shapecustom2);
        shapecustom2.setLayout(shapecustom2Layout);
        shapecustom2Layout.setHorizontalGroup(
            shapecustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        shapecustom2Layout.setVerticalGroup(
            shapecustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        shapecustom3.setBackground(new java.awt.Color(212, 212, 212));
        shapecustom3.setRoundBottomLeft(40);
        shapecustom3.setRoundBottomRight(40);
        shapecustom3.setRoundTopLeft(40);
        shapecustom3.setRoundTopRight(40);

        javax.swing.GroupLayout shapecustom3Layout = new javax.swing.GroupLayout(shapecustom3);
        shapecustom3.setLayout(shapecustom3Layout);
        shapecustom3Layout.setHorizontalGroup(
            shapecustom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        shapecustom3Layout.setVerticalGroup(
            shapecustom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        shapecustom4.setBackground(new java.awt.Color(212, 212, 212));
        shapecustom4.setRoundBottomLeft(40);
        shapecustom4.setRoundBottomRight(40);
        shapecustom4.setRoundTopLeft(40);
        shapecustom4.setRoundTopRight(40);

        javax.swing.GroupLayout shapecustom4Layout = new javax.swing.GroupLayout(shapecustom4);
        shapecustom4.setLayout(shapecustom4Layout);
        shapecustom4Layout.setHorizontalGroup(
            shapecustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        shapecustom4Layout.setVerticalGroup(
            shapecustom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        shapecustom5.setBackground(new java.awt.Color(1, 80, 22));
        shapecustom5.setRoundBottomLeft(80);
        shapecustom5.setRoundBottomRight(80);
        shapecustom5.setRoundTopLeft(80);
        shapecustom5.setRoundTopRight(80);

        shapecustom6.setBackground(new java.awt.Color(255, 255, 255));
        shapecustom6.setRoundBottomLeft(40);
        shapecustom6.setRoundBottomRight(40);
        shapecustom6.setRoundTopLeft(40);
        shapecustom6.setRoundTopRight(40);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ananta/ui/ux/icon_search.png"))); // NOI18N

        javax.swing.GroupLayout shapecustom6Layout = new javax.swing.GroupLayout(shapecustom6);
        shapecustom6.setLayout(shapecustom6Layout);
        shapecustom6Layout.setHorizontalGroup(
            shapecustom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shapecustom6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(674, Short.MAX_VALUE))
        );
        shapecustom6Layout.setVerticalGroup(
            shapecustom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout shapecustom5Layout = new javax.swing.GroupLayout(shapecustom5);
        shapecustom5.setLayout(shapecustom5Layout);
        shapecustom5Layout.setHorizontalGroup(
            shapecustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shapecustom5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(shapecustom6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        shapecustom5Layout.setVerticalGroup(
            shapecustom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shapecustom5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(shapecustom6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(739, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 30)); // NOI18N
        jLabel5.setText("Available Hair Package");

        shapecustom7.setBackground(new java.awt.Color(212, 212, 212));
        shapecustom7.setRoundBottomLeft(40);
        shapecustom7.setRoundBottomRight(40);
        shapecustom7.setRoundTopLeft(40);
        shapecustom7.setRoundTopRight(40);

        javax.swing.GroupLayout shapecustom7Layout = new javax.swing.GroupLayout(shapecustom7);
        shapecustom7.setLayout(shapecustom7Layout);
        shapecustom7Layout.setHorizontalGroup(
            shapecustom7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        shapecustom7Layout.setVerticalGroup(
            shapecustom7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 1, 25)); // NOI18N
        jLabel7.setText("Jasa Tambahan");

        shapecustom9.setBackground(new java.awt.Color(76, 175, 80));
        shapecustom9.setPreferredSize(new java.awt.Dimension(125, 45));
        shapecustom9.setRoundBottomLeft(30);
        shapecustom9.setRoundBottomRight(30);
        shapecustom9.setRoundTopLeft(30);
        shapecustom9.setRoundTopRight(30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ananta/ui/ux/icon_simpan.png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(76, 175, 80));
        jButton1.setFont(new java.awt.Font("Book Antiqua", 1, 17)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Simpan");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout shapecustom9Layout = new javax.swing.GroupLayout(shapecustom9);
        shapecustom9.setLayout(shapecustom9Layout);
        shapecustom9Layout.setHorizontalGroup(
            shapecustom9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shapecustom9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        shapecustom9Layout.setVerticalGroup(
            shapecustom9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(shapecustom9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        shapecustom10.setBackground(new java.awt.Color(255, 152, 0));
        shapecustom10.setPreferredSize(new java.awt.Dimension(125, 45));
        shapecustom10.setRoundBottomLeft(30);
        shapecustom10.setRoundBottomRight(30);
        shapecustom10.setRoundTopLeft(30);
        shapecustom10.setRoundTopRight(30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ananta/ui/ux/icon_batal.png"))); // NOI18N

        jButton2.setBackground(new java.awt.Color(255, 152, 0));
        jButton2.setFont(new java.awt.Font("Book Antiqua", 1, 17)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Batal");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout shapecustom10Layout = new javax.swing.GroupLayout(shapecustom10);
        shapecustom10.setLayout(shapecustom10Layout);
        shapecustom10Layout.setHorizontalGroup(
            shapecustom10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shapecustom10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(0, 0, 0)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addContainerGap())
        );
        shapecustom10Layout.setVerticalGroup(
            shapecustom10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(shapecustom10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        shapecustom11.setBackground(new java.awt.Color(202, 0, 0));
        shapecustom11.setPreferredSize(new java.awt.Dimension(125, 45));
        shapecustom11.setRoundBottomLeft(30);
        shapecustom11.setRoundBottomRight(30);
        shapecustom11.setRoundTopLeft(30);
        shapecustom11.setRoundTopRight(30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ananta/ui/ux/icon_hapus.png"))); // NOI18N

        jButton3.setBackground(new java.awt.Color(202, 0, 0));
        jButton3.setFont(new java.awt.Font("Book Antiqua", 1, 17)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Hapus");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout shapecustom11Layout = new javax.swing.GroupLayout(shapecustom11);
        shapecustom11.setLayout(shapecustom11Layout);
        shapecustom11Layout.setHorizontalGroup(
            shapecustom11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shapecustom11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addContainerGap())
        );
        shapecustom11Layout.setVerticalGroup(
            shapecustom11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(shapecustom11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel_TambahJasa1.setBackground(new java.awt.Color(33, 150, 243));
        Panel_TambahJasa1.setPreferredSize(new java.awt.Dimension(125, 45));
        Panel_TambahJasa1.setRoundBottomLeft(30);
        Panel_TambahJasa1.setRoundBottomRight(30);
        Panel_TambahJasa1.setRoundTopLeft(30);
        Panel_TambahJasa1.setRoundTopRight(30);

        Button_TambahJasa1.setBackground(new java.awt.Color(33, 150, 243));
        Button_TambahJasa1.setFont(new java.awt.Font("Book Antiqua", 1, 17)); // NOI18N
        Button_TambahJasa1.setForeground(new java.awt.Color(255, 255, 255));
        Button_TambahJasa1.setText("Tambah");
        Button_TambahJasa1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Button_TambahJasa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TambahJasa1ActionPerformed(evt);
            }
        });

        Ikon_TambahJasa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ikon_TambahJasa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ananta/ui/ux/icon_tambah.png"))); // NOI18N

        javax.swing.GroupLayout Panel_TambahJasa1Layout = new javax.swing.GroupLayout(Panel_TambahJasa1);
        Panel_TambahJasa1.setLayout(Panel_TambahJasa1Layout);
        Panel_TambahJasa1Layout.setHorizontalGroup(
            Panel_TambahJasa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_TambahJasa1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ikon_TambahJasa1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Button_TambahJasa1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addContainerGap())
        );
        Panel_TambahJasa1Layout.setVerticalGroup(
            Panel_TambahJasa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ikon_TambahJasa1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
            .addGroup(Panel_TambahJasa1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_TambahJasa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout shapecustom1Layout = new javax.swing.GroupLayout(shapecustom1);
        shapecustom1.setLayout(shapecustom1Layout);
        shapecustom1Layout.setHorizontalGroup(
            shapecustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shapecustom1Layout.createSequentialGroup()
                .addGroup(shapecustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shapecustom1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(shapecustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(shapecustom1Layout.createSequentialGroup()
                                .addGroup(shapecustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(shapecustom1Layout.createSequentialGroup()
                                .addComponent(shapecustom9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(shapecustom10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(shapecustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(shapecustom1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(shapecustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(shapecustom4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(shapecustom2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(shapecustom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(shapecustom7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(shapecustom1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(Panel_TambahJasa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(shapecustom11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(101, 101, 101))
                    .addGroup(shapecustom1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addGap(464, 474, Short.MAX_VALUE)))
                .addGroup(shapecustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(shapecustom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        shapecustom1Layout.setVerticalGroup(
            shapecustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shapecustom1Layout.createSequentialGroup()
                .addGroup(shapecustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(shapecustom1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(shapecustom1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(shapecustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(shapecustom1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(shapecustom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(shapecustom1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(shapecustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shapecustom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(shapecustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shapecustom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(shapecustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shapecustom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(shapecustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shapecustom7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(shapecustom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shapecustom9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shapecustom10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Panel_TambahJasa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shapecustom11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(211, 211, 211))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(shapecustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(shapecustom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Button_TambahJasa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_TambahJasa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_TambahJasa1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_TambahJasa1;
    private javax.swing.JLabel Ikon_TambahJasa1;
    private com.ananta.shapecustom.shapecustom Panel_TambahJasa1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.ananta.shapecustom.shapecustom shapecustom1;
    private com.ananta.shapecustom.shapecustom shapecustom10;
    private com.ananta.shapecustom.shapecustom shapecustom11;
    private com.ananta.shapecustom.shapecustom shapecustom2;
    private com.ananta.shapecustom.shapecustom shapecustom3;
    private com.ananta.shapecustom.shapecustom shapecustom4;
    private com.ananta.shapecustom.shapecustom shapecustom5;
    private com.ananta.shapecustom.shapecustom shapecustom6;
    private com.ananta.shapecustom.shapecustom shapecustom7;
    private com.ananta.shapecustom.shapecustom shapecustom9;
    // End of variables declaration//GEN-END:variables
}
