/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ananta.form;

/**
 *
 * @author M.Khoiril
 */
public class cc1 extends javax.swing.JPanel {

    /**
     * Creates new form cc
     */
    public cc1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_hitam_Pengeluaran = new com.ananta.shape.shapecustom();
        shapecustom6 = new com.ananta.shape.shapecustom();
        IdPengeluaram = new javax.swing.JLabel();
        shapecustom7 = new com.ananta.shape.shapecustom();
        fieldIdPengeluaran = new javax.swing.JTextField();
        NamaKasir = new javax.swing.JLabel();
        shapecustom16 = new com.ananta.shape.shapecustom();
        fieldNamaKasir = new javax.swing.JTextField();
        label_Pengeluaran = new javax.swing.JLabel();
        btn_simpanORdetail = new com.ananta.shape.CustomButton();
        JenisPengeluaran = new javax.swing.JLabel();
        shapecustom14 = new com.ananta.shape.shapecustom();
        cbbx_pilihKategori = new com.ananta.shape.CustomComboBox();
        TotalHarga = new javax.swing.JLabel();
        shapecustom9 = new com.ananta.shape.shapecustom();
        fieldTotalHarga = new javax.swing.JTextField();
        pn_hitam_Fdetail = new com.ananta.shape.shapecustom();
        pn_abu_detail = new com.ananta.shape.shapecustom();
        label_Detailrestock = new javax.swing.JLabel();
        PilihBarang = new javax.swing.JLabel();
        shapecustom10 = new com.ananta.shape.shapecustom();
        cbbx_pilihBarang = new com.ananta.shape.CustomComboBox();
        shapecustom11 = new com.ananta.shape.shapecustom();
        jTextField10 = new javax.swing.JTextField();
        IdBarang = new javax.swing.JLabel();
        btn_simpanORdetail1 = new com.ananta.shape.CustomButton();
        Barcode = new javax.swing.JLabel();
        shapecustom12 = new com.ananta.shape.shapecustom();
        fieldBarcode = new javax.swing.JTextField();
        shapecustom13 = new com.ananta.shape.shapecustom();
        fieldJumlahBeli = new javax.swing.JTextField();
        JumlahBeli = new javax.swing.JLabel();
        shapecustom15 = new com.ananta.shape.shapecustom();
        fieldTotalBiaya = new javax.swing.JTextField();
        TotalBiaya = new javax.swing.JLabel();
        pn_hitam_Ddetail = new com.ananta.shape.shapecustom();
        shapecustom8 = new com.ananta.shape.shapecustom();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabeel2 = new com.ananta.shape.JTabeel();
        label_Detailrestock2 = new javax.swing.JLabel();
        btn_edit = new com.ananta.shape.CustomButton();
        btn_batal_DPengeluaran = new com.ananta.shape.CustomButton();
        btn_hapus = new com.ananta.shape.CustomButton();
        pn_hitam_DPengeluaran = new com.ananta.shape.shapecustom();
        pn_abu_tabel = new com.ananta.shape.shapecustom();
        label_DaftarPengeluaran = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabeel1 = new com.ananta.shape.JTabeel();

        pn_hitam_Pengeluaran.setBackground(new java.awt.Color(1, 0, 0));
        pn_hitam_Pengeluaran.setRoundBottomLeft(60);
        pn_hitam_Pengeluaran.setRoundBottomRight(60);
        pn_hitam_Pengeluaran.setRoundTopLeft(60);
        pn_hitam_Pengeluaran.setRoundTopRight(60);

        shapecustom6.setBackground(new java.awt.Color(204, 204, 204));
        shapecustom6.setRoundBottomLeft(60);
        shapecustom6.setRoundBottomRight(60);
        shapecustom6.setRoundTopLeft(60);
        shapecustom6.setRoundTopRight(60);

        IdPengeluaram.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        IdPengeluaram.setForeground(new java.awt.Color(1, 0, 0));
        IdPengeluaram.setText("ID Pengeluaran");

        shapecustom7.setBackground(new java.awt.Color(235, 235, 235));
        shapecustom7.setRoundBottomLeft(20);
        shapecustom7.setRoundBottomRight(20);
        shapecustom7.setRoundTopLeft(20);
        shapecustom7.setRoundTopRight(20);

        fieldIdPengeluaran.setBackground(new java.awt.Color(235, 235, 235));
        fieldIdPengeluaran.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        fieldIdPengeluaran.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        fieldIdPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIdPengeluaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout shapecustom7Layout = new javax.swing.GroupLayout(shapecustom7);
        shapecustom7.setLayout(shapecustom7Layout);
        shapecustom7Layout.setHorizontalGroup(
            shapecustom7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shapecustom7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldIdPengeluaran)
                .addContainerGap())
        );
        shapecustom7Layout.setVerticalGroup(
            shapecustom7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shapecustom7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldIdPengeluaran)
                .addContainerGap())
        );

        NamaKasir.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        NamaKasir.setForeground(new java.awt.Color(1, 0, 0));
        NamaKasir.setText("Nama Kasir");

        shapecustom16.setBackground(new java.awt.Color(235, 235, 235));
        shapecustom16.setRoundBottomLeft(20);
        shapecustom16.setRoundBottomRight(20);
        shapecustom16.setRoundTopLeft(20);
        shapecustom16.setRoundTopRight(20);

        fieldNamaKasir.setBackground(new java.awt.Color(235, 235, 235));
        fieldNamaKasir.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        fieldNamaKasir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        fieldNamaKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNamaKasirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout shapecustom16Layout = new javax.swing.GroupLayout(shapecustom16);
        shapecustom16.setLayout(shapecustom16Layout);
        shapecustom16Layout.setHorizontalGroup(
            shapecustom16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shapecustom16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldNamaKasir)
                .addContainerGap())
        );
        shapecustom16Layout.setVerticalGroup(
            shapecustom16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shapecustom16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldNamaKasir, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        label_Pengeluaran.setFont(new java.awt.Font("Bookman Old Style", 1, 30)); // NOI18N
        label_Pengeluaran.setForeground(new java.awt.Color(1, 0, 0));
        label_Pengeluaran.setText("Form Pengeluaran");

        btn_simpanORdetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ananta/icon/icon_simpan.png"))); // NOI18N
        btn_simpanORdetail.setText("Simpan");
        btn_simpanORdetail.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        btn_simpanORdetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanORdetailActionPerformed(evt);
            }
        });

        JenisPengeluaran.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        JenisPengeluaran.setForeground(new java.awt.Color(1, 0, 0));
        JenisPengeluaran.setText("Kategori");

        shapecustom14.setBackground(new java.awt.Color(255, 252, 253));
        shapecustom14.setRoundBottomLeft(20);
        shapecustom14.setRoundBottomRight(20);
        shapecustom14.setRoundTopLeft(20);
        shapecustom14.setRoundTopRight(20);

        cbbx_pilihKategori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Kategori", "Opsi 1", "Opsi 2", "Opsi 3" }));
        cbbx_pilihKategori.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        cbbx_pilihKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbx_pilihKategoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout shapecustom14Layout = new javax.swing.GroupLayout(shapecustom14);
        shapecustom14.setLayout(shapecustom14Layout);
        shapecustom14Layout.setHorizontalGroup(
            shapecustom14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shapecustom14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbbx_pilihKategori, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );
        shapecustom14Layout.setVerticalGroup(
            shapecustom14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shapecustom14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbbx_pilihKategori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TotalHarga.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        TotalHarga.setForeground(new java.awt.Color(1, 0, 0));
        TotalHarga.setText("Total Biaya");

        shapecustom9.setBackground(new java.awt.Color(255, 252, 253));
        shapecustom9.setRoundBottomLeft(20);
        shapecustom9.setRoundBottomRight(20);
        shapecustom9.setRoundTopLeft(20);
        shapecustom9.setRoundTopRight(20);

        fieldTotalHarga.setBackground(new java.awt.Color(255, 253, 253));
        fieldTotalHarga.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        fieldTotalHarga.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        fieldTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTotalHargaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout shapecustom9Layout = new javax.swing.GroupLayout(shapecustom9);
        shapecustom9.setLayout(shapecustom9Layout);
        shapecustom9Layout.setHorizontalGroup(
            shapecustom9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shapecustom9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldTotalHarga)
                .addContainerGap())
        );
        shapecustom9Layout.setVerticalGroup(
            shapecustom9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shapecustom9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldTotalHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout shapecustom6Layout = new javax.swing.GroupLayout(shapecustom6);
        shapecustom6.setLayout(shapecustom6Layout);
        shapecustom6Layout.setHorizontalGroup(
            shapecustom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shapecustom6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(shapecustom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_Pengeluaran)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shapecustom6Layout.createSequentialGroup()
                        .addGroup(shapecustom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(shapecustom6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_simpanORdetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(shapecustom6Layout.createSequentialGroup()
                                .addGroup(shapecustom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(shapecustom6Layout.createSequentialGroup()
                                        .addGroup(shapecustom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(JenisPengeluaran, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(NamaKasir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(IdPengeluaram, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shapecustom6Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(TotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(shapecustom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(shapecustom14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(shapecustom16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(shapecustom7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(shapecustom9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(50, 50, 50))))
        );
        shapecustom6Layout.setVerticalGroup(
            shapecustom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shapecustom6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(label_Pengeluaran)
                .addGap(25, 25, 25)
                .addGroup(shapecustom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(shapecustom7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IdPengeluaram, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(shapecustom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NamaKasir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shapecustom16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(shapecustom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(shapecustom14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JenisPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(shapecustom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TotalHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shapecustom9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btn_simpanORdetail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_hitam_PengeluaranLayout = new javax.swing.GroupLayout(pn_hitam_Pengeluaran);
        pn_hitam_Pengeluaran.setLayout(pn_hitam_PengeluaranLayout);
        pn_hitam_PengeluaranLayout.setHorizontalGroup(
            pn_hitam_PengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_hitam_PengeluaranLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(shapecustom6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_hitam_PengeluaranLayout.setVerticalGroup(
            pn_hitam_PengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_hitam_PengeluaranLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shapecustom6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_hitam_Fdetail.setBackground(new java.awt.Color(1, 0, 0));
        pn_hitam_Fdetail.setForeground(new java.awt.Color(255, 255, 255));
        pn_hitam_Fdetail.setRoundBottomLeft(60);
        pn_hitam_Fdetail.setRoundBottomRight(60);
        pn_hitam_Fdetail.setRoundTopLeft(60);
        pn_hitam_Fdetail.setRoundTopRight(60);

        pn_abu_detail.setBackground(new java.awt.Color(204, 204, 204));
        pn_abu_detail.setRoundBottomLeft(60);
        pn_abu_detail.setRoundBottomRight(60);
        pn_abu_detail.setRoundTopLeft(60);
        pn_abu_detail.setRoundTopRight(60);

        label_Detailrestock.setFont(new java.awt.Font("Bookman Old Style", 1, 30)); // NOI18N
        label_Detailrestock.setForeground(new java.awt.Color(1, 0, 0));
        label_Detailrestock.setText("Form Detail ReStock");

        PilihBarang.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        PilihBarang.setForeground(new java.awt.Color(1, 0, 0));
        PilihBarang.setText("Pilih Barang");

        shapecustom10.setBackground(new java.awt.Color(255, 252, 253));
        shapecustom10.setRoundBottomLeft(20);
        shapecustom10.setRoundBottomRight(20);
        shapecustom10.setRoundTopLeft(20);
        shapecustom10.setRoundTopRight(20);

        cbbx_pilihBarang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Barang", "Opsi 1", "Opsi 2", "Opsi 3" }));
        cbbx_pilihBarang.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        cbbx_pilihBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbx_pilihBarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout shapecustom10Layout = new javax.swing.GroupLayout(shapecustom10);
        shapecustom10.setLayout(shapecustom10Layout);
        shapecustom10Layout.setHorizontalGroup(
            shapecustom10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shapecustom10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbbx_pilihBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );
        shapecustom10Layout.setVerticalGroup(
            shapecustom10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shapecustom10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbbx_pilihBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        shapecustom11.setBackground(new java.awt.Color(235, 235, 235));
        shapecustom11.setRoundBottomLeft(20);
        shapecustom11.setRoundBottomRight(20);
        shapecustom11.setRoundTopLeft(20);
        shapecustom11.setRoundTopRight(20);

        jTextField10.setBackground(new java.awt.Color(235, 235, 235));
        jTextField10.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jTextField10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout shapecustom11Layout = new javax.swing.GroupLayout(shapecustom11);
        shapecustom11.setLayout(shapecustom11Layout);
        shapecustom11Layout.setHorizontalGroup(
            shapecustom11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shapecustom11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );
        shapecustom11Layout.setVerticalGroup(
            shapecustom11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shapecustom11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField10)
                .addContainerGap())
        );

        IdBarang.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        IdBarang.setForeground(new java.awt.Color(1, 0, 0));
        IdBarang.setText("ID Barang");

        btn_simpanORdetail1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ananta/icon/icon_simpan.png"))); // NOI18N
        btn_simpanORdetail1.setText("Simpan");
        btn_simpanORdetail1.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        btn_simpanORdetail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanORdetail1ActionPerformed(evt);
            }
        });

        Barcode.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        Barcode.setForeground(new java.awt.Color(1, 0, 0));
        Barcode.setText("Barcode");

        shapecustom12.setBackground(new java.awt.Color(235, 235, 235));
        shapecustom12.setRoundBottomLeft(20);
        shapecustom12.setRoundBottomRight(20);
        shapecustom12.setRoundTopLeft(20);
        shapecustom12.setRoundTopRight(20);

        fieldBarcode.setBackground(new java.awt.Color(235, 235, 235));
        fieldBarcode.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        fieldBarcode.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        fieldBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldBarcodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout shapecustom12Layout = new javax.swing.GroupLayout(shapecustom12);
        shapecustom12.setLayout(shapecustom12Layout);
        shapecustom12Layout.setHorizontalGroup(
            shapecustom12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shapecustom12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldBarcode, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );
        shapecustom12Layout.setVerticalGroup(
            shapecustom12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shapecustom12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldBarcode)
                .addContainerGap())
        );

        shapecustom13.setBackground(new java.awt.Color(255, 252, 253));
        shapecustom13.setRoundBottomLeft(20);
        shapecustom13.setRoundBottomRight(20);
        shapecustom13.setRoundTopLeft(20);
        shapecustom13.setRoundTopRight(20);

        fieldJumlahBeli.setBackground(new java.awt.Color(255, 253, 253));
        fieldJumlahBeli.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        fieldJumlahBeli.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        fieldJumlahBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldJumlahBeliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout shapecustom13Layout = new javax.swing.GroupLayout(shapecustom13);
        shapecustom13.setLayout(shapecustom13Layout);
        shapecustom13Layout.setHorizontalGroup(
            shapecustom13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shapecustom13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldJumlahBeli, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );
        shapecustom13Layout.setVerticalGroup(
            shapecustom13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shapecustom13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldJumlahBeli)
                .addContainerGap())
        );

        JumlahBeli.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        JumlahBeli.setForeground(new java.awt.Color(1, 0, 0));
        JumlahBeli.setText("Jumlah Beli");

        shapecustom15.setBackground(new java.awt.Color(255, 252, 253));
        shapecustom15.setRoundBottomLeft(20);
        shapecustom15.setRoundBottomRight(20);
        shapecustom15.setRoundTopLeft(20);
        shapecustom15.setRoundTopRight(20);

        fieldTotalBiaya.setBackground(new java.awt.Color(255, 253, 253));
        fieldTotalBiaya.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        fieldTotalBiaya.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        fieldTotalBiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTotalBiayaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout shapecustom15Layout = new javax.swing.GroupLayout(shapecustom15);
        shapecustom15.setLayout(shapecustom15Layout);
        shapecustom15Layout.setHorizontalGroup(
            shapecustom15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shapecustom15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldTotalBiaya, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );
        shapecustom15Layout.setVerticalGroup(
            shapecustom15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shapecustom15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldTotalBiaya)
                .addContainerGap())
        );

        TotalBiaya.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        TotalBiaya.setForeground(new java.awt.Color(1, 0, 0));
        TotalBiaya.setText("Total Biaya");

        javax.swing.GroupLayout pn_abu_detailLayout = new javax.swing.GroupLayout(pn_abu_detail);
        pn_abu_detail.setLayout(pn_abu_detailLayout);
        pn_abu_detailLayout.setHorizontalGroup(
            pn_abu_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_abu_detailLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pn_abu_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_Detailrestock)
                    .addComponent(PilihBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_abu_detailLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pn_abu_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(shapecustom10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_simpanORdetail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shapecustom11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shapecustom12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shapecustom13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shapecustom15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        pn_abu_detailLayout.setVerticalGroup(
            pn_abu_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_abu_detailLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(label_Detailrestock)
                .addGap(28, 28, 28)
                .addGroup(pn_abu_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(shapecustom10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PilihBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pn_abu_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(shapecustom11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pn_abu_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(shapecustom12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pn_abu_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(shapecustom13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pn_abu_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(shapecustom15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TotalBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_simpanORdetail1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_hitam_FdetailLayout = new javax.swing.GroupLayout(pn_hitam_Fdetail);
        pn_hitam_Fdetail.setLayout(pn_hitam_FdetailLayout);
        pn_hitam_FdetailLayout.setHorizontalGroup(
            pn_hitam_FdetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_hitam_FdetailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_abu_detail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_hitam_FdetailLayout.setVerticalGroup(
            pn_hitam_FdetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_hitam_FdetailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_abu_detail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pn_hitam_Ddetail.setBackground(new java.awt.Color(1, 0, 0));
        pn_hitam_Ddetail.setForeground(new java.awt.Color(255, 255, 255));
        pn_hitam_Ddetail.setRoundBottomLeft(60);
        pn_hitam_Ddetail.setRoundBottomRight(60);
        pn_hitam_Ddetail.setRoundTopLeft(60);
        pn_hitam_Ddetail.setRoundTopRight(60);

        shapecustom8.setBackground(new java.awt.Color(204, 204, 204));
        shapecustom8.setRoundBottomLeft(60);
        shapecustom8.setRoundBottomRight(60);
        shapecustom8.setRoundTopLeft(60);
        shapecustom8.setRoundTopRight(60);

        jTabeel2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, "Rp29.000.000,00"},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID PENGELUARAN", "ID BARANG", "BARCODE", "JUMLAH BELI", "NAMA BARANG", "TOTAL BIAYA"
            }
        ));
        jScrollPane2.setViewportView(jTabeel2);

        label_Detailrestock2.setFont(new java.awt.Font("Bookman Old Style", 1, 30)); // NOI18N
        label_Detailrestock2.setForeground(new java.awt.Color(1, 0, 0));
        label_Detailrestock2.setText("Daftar Detail ReStock");

        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ananta/ui/ux/icons8-edit-30.png"))); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_batal_DPengeluaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ananta/icon/icon_batal.png"))); // NOI18N
        btn_batal_DPengeluaran.setText("Batal");
        btn_batal_DPengeluaran.setDefaultColor(new java.awt.Color(255, 153, 0));
        btn_batal_DPengeluaran.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        btn_batal_DPengeluaran.setHoverColor(new java.awt.Color(255, 102, 0));
        btn_batal_DPengeluaran.setPressedColor(new java.awt.Color(204, 102, 0));
        btn_batal_DPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batal_DPengeluaranActionPerformed(evt);
            }
        });

        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ananta/icon/icon_hapus.png"))); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.setDefaultColor(new java.awt.Color(255, 51, 51));
        btn_hapus.setFont(new java.awt.Font("Cambria", 1, 15)); // NOI18N
        btn_hapus.setHoverColor(new java.awt.Color(255, 0, 0));
        btn_hapus.setPressedColor(new java.awt.Color(153, 0, 0));
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout shapecustom8Layout = new javax.swing.GroupLayout(shapecustom8);
        shapecustom8.setLayout(shapecustom8Layout);
        shapecustom8Layout.setHorizontalGroup(
            shapecustom8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shapecustom8Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(shapecustom8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(shapecustom8Layout.createSequentialGroup()
                        .addComponent(label_Detailrestock2)
                        .addGap(31, 31, 31)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_batal_DPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        shapecustom8Layout.setVerticalGroup(
            shapecustom8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shapecustom8Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(shapecustom8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_Detailrestock2)
                    .addGroup(shapecustom8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_batal_DPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_hitam_DdetailLayout = new javax.swing.GroupLayout(pn_hitam_Ddetail);
        pn_hitam_Ddetail.setLayout(pn_hitam_DdetailLayout);
        pn_hitam_DdetailLayout.setHorizontalGroup(
            pn_hitam_DdetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_hitam_DdetailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shapecustom8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_hitam_DdetailLayout.setVerticalGroup(
            pn_hitam_DdetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_hitam_DdetailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shapecustom8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pn_hitam_DPengeluaran.setBackground(new java.awt.Color(1, 0, 0));
        pn_hitam_DPengeluaran.setRoundBottomLeft(60);
        pn_hitam_DPengeluaran.setRoundBottomRight(60);
        pn_hitam_DPengeluaran.setRoundTopLeft(60);
        pn_hitam_DPengeluaran.setRoundTopRight(60);

        pn_abu_tabel.setBackground(new java.awt.Color(204, 204, 204));
        pn_abu_tabel.setRoundBottomLeft(60);
        pn_abu_tabel.setRoundBottomRight(60);
        pn_abu_tabel.setRoundTopLeft(60);
        pn_abu_tabel.setRoundTopRight(60);

        label_DaftarPengeluaran.setFont(new java.awt.Font("Bookman Old Style", 1, 30)); // NOI18N
        label_DaftarPengeluaran.setForeground(new java.awt.Color(1, 0, 0));
        label_DaftarPengeluaran.setText("Daftar Pengeluaran");

        jTabeel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID PENGELUARAN", "NAMA KASIR", "KATEGORI", "TOTAL BIAYA", "AKSI"
            }
        ));
        jScrollPane1.setViewportView(jTabeel1);

        javax.swing.GroupLayout pn_abu_tabelLayout = new javax.swing.GroupLayout(pn_abu_tabel);
        pn_abu_tabel.setLayout(pn_abu_tabelLayout);
        pn_abu_tabelLayout.setHorizontalGroup(
            pn_abu_tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_abu_tabelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pn_abu_tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_DaftarPengeluaran)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        pn_abu_tabelLayout.setVerticalGroup(
            pn_abu_tabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_abu_tabelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(label_DaftarPengeluaran)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_hitam_DPengeluaranLayout = new javax.swing.GroupLayout(pn_hitam_DPengeluaran);
        pn_hitam_DPengeluaran.setLayout(pn_hitam_DPengeluaranLayout);
        pn_hitam_DPengeluaranLayout.setHorizontalGroup(
            pn_hitam_DPengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_hitam_DPengeluaranLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_abu_tabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_hitam_DPengeluaranLayout.setVerticalGroup(
            pn_hitam_DPengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_hitam_DPengeluaranLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_abu_tabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pn_hitam_Pengeluaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_hitam_Fdetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_hitam_DPengeluaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_hitam_Ddetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pn_hitam_DPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pn_hitam_Ddetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pn_hitam_Pengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pn_hitam_Fdetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldTotalBiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTotalBiayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTotalBiayaActionPerformed

    private void fieldJumlahBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldJumlahBeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldJumlahBeliActionPerformed

    private void fieldBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldBarcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldBarcodeActionPerformed

    private void btn_simpanORdetail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanORdetail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_simpanORdetail1ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void cbbx_pilihBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbx_pilihBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbx_pilihBarangActionPerformed

    private void fieldTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTotalHargaActionPerformed
        ;        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTotalHargaActionPerformed

    private void cbbx_pilihKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbx_pilihKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbx_pilihKategoriActionPerformed

    private void btn_simpanORdetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanORdetailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_simpanORdetailActionPerformed

    private void fieldNamaKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNamaKasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNamaKasirActionPerformed

    private void fieldIdPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIdPengeluaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIdPengeluaranActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed

    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_batal_DPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batal_DPengeluaranActionPerformed

    }//GEN-LAST:event_btn_batal_DPengeluaranActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed

    }//GEN-LAST:event_btn_hapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Barcode;
    private javax.swing.JLabel IdBarang;
    private javax.swing.JLabel IdPengeluaram;
    private javax.swing.JLabel JenisPengeluaran;
    private javax.swing.JLabel JumlahBeli;
    private javax.swing.JLabel NamaKasir;
    private javax.swing.JLabel PilihBarang;
    private javax.swing.JLabel TotalBiaya;
    private javax.swing.JLabel TotalHarga;
    private com.ananta.shape.CustomButton btn_batal_DPengeluaran;
    private com.ananta.shape.CustomButton btn_edit;
    private com.ananta.shape.CustomButton btn_hapus;
    private com.ananta.shape.CustomButton btn_simpanORdetail;
    private com.ananta.shape.CustomButton btn_simpanORdetail1;
    private com.ananta.shape.CustomComboBox cbbx_pilihBarang;
    private com.ananta.shape.CustomComboBox cbbx_pilihKategori;
    private javax.swing.JTextField fieldBarcode;
    private javax.swing.JTextField fieldIdPengeluaran;
    private javax.swing.JTextField fieldJumlahBeli;
    private javax.swing.JTextField fieldNamaKasir;
    private javax.swing.JTextField fieldTotalBiaya;
    private javax.swing.JTextField fieldTotalHarga;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.ananta.shape.JTabeel jTabeel1;
    private com.ananta.shape.JTabeel jTabeel2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JLabel label_DaftarPengeluaran;
    private javax.swing.JLabel label_Detailrestock;
    private javax.swing.JLabel label_Detailrestock2;
    private javax.swing.JLabel label_Pengeluaran;
    private com.ananta.shape.shapecustom pn_abu_detail;
    private com.ananta.shape.shapecustom pn_abu_tabel;
    private com.ananta.shape.shapecustom pn_hitam_DPengeluaran;
    private com.ananta.shape.shapecustom pn_hitam_Ddetail;
    private com.ananta.shape.shapecustom pn_hitam_Fdetail;
    private com.ananta.shape.shapecustom pn_hitam_Pengeluaran;
    private com.ananta.shape.shapecustom shapecustom10;
    private com.ananta.shape.shapecustom shapecustom11;
    private com.ananta.shape.shapecustom shapecustom12;
    private com.ananta.shape.shapecustom shapecustom13;
    private com.ananta.shape.shapecustom shapecustom14;
    private com.ananta.shape.shapecustom shapecustom15;
    private com.ananta.shape.shapecustom shapecustom16;
    private com.ananta.shape.shapecustom shapecustom6;
    private com.ananta.shape.shapecustom shapecustom7;
    private com.ananta.shape.shapecustom shapecustom8;
    private com.ananta.shape.shapecustom shapecustom9;
    // End of variables declaration//GEN-END:variables
}
